// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI.Data;

#nullable disable

namespace THUEXERE.Migrations
{
    [DbContext(typeof(WebDbContext))]
    partial class WebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPI.Data.AnhNoiDung", b =>
                {
                    b.Property<string>("MaAnh")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNoiDung")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaNoiDung");

                    b.ToTable("AnhNoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.BaiViet", b =>
                {
                    b.Property<string>("MaBV")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhMinhHoaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanhMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaND")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MoDau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBV");

                    b.HasIndex("MaND");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("WEBAPI.Data.BangGia", b =>
                {
                    b.Property<string>("MaBangGia")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<float>("Gia11Den15")
                        .HasColumnType("real");

                    b.Property<float>("Gia16Den20")
                        .HasColumnType("real");

                    b.Property<float>("Gia1Den5")
                        .HasColumnType("real");

                    b.Property<float>("Gia21Den30")
                        .HasColumnType("real");

                    b.Property<float>("Gia31")
                        .HasColumnType("real");

                    b.Property<float>("Gia6Den10")
                        .HasColumnType("real");

                    b.Property<string>("MaXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaBangGia");

                    b.HasIndex("MaXe");

                    b.ToTable("BangGia");
                });

            modelBuilder.Entity("WEBAPI.Data.ChiTietDonThue", b =>
                {
                    b.Property<string>("MaCTDT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhMinhChungURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaHan")
                        .HasColumnType("int");

                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("real");

                    b.Property<float>("TienCoc")
                        .HasColumnType("real");

                    b.Property<float>("TienCocGiuXe")
                        .HasColumnType("real");

                    b.Property<string>("TinhTrangBanGiao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCTDT");

                    b.HasIndex("MaDT");

                    b.ToTable("ChiTietDonThue");
                });

            modelBuilder.Entity("WEBAPI.Data.DanhMucXe", b =>
                {
                    b.Property<string>("IdDanhMuc")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("TenXe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("DanhMucXe");
                });

            modelBuilder.Entity("WEBAPI.Data.DichVu", b =>
                {
                    b.Property<string>("MaDV")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhMinhHoaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("WEBAPI.Data.DonThue", b =>
                {
                    b.Property<string>("MaDT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaNVHT")
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.HasKey("MaDT");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNVHT");

                    b.ToTable("DonThue");
                });

            modelBuilder.Entity("WEBAPI.Data.DonThue_DichVu", b =>
                {
                    b.Property<string>("MaDV")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaDT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("MaDV", "MaDT");

                    b.HasIndex("MaDT");

                    b.ToTable("DonThue_DichVu");
                });

            modelBuilder.Entity("WEBAPI.Data.GopY", b =>
                {
                    b.Property<string>("MaGY")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaDT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGY");

                    b.HasIndex("MaDT");

                    b.ToTable("GopY");
                });

            modelBuilder.Entity("WEBAPI.Data.LoaiXe", b =>
                {
                    b.Property<string>("IdLoaiXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("loaiXe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdLoaiXe");

                    b.ToTable("LoaiXe");
                });

            modelBuilder.Entity("WEBAPI.Data.MauXe", b =>
                {
                    b.Property<string>("IdMauXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("mauXe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdMauXe");

                    b.ToTable("MauXe");
                });

            modelBuilder.Entity("WEBAPI.Data.NguoiDung", b =>
                {
                    b.Property<string>("MaND")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaND");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.NoiDung", b =>
                {
                    b.Property<string>("MaNoiDung")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaBV")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNoiDung");

                    b.HasIndex("MaBV");

                    b.ToTable("NoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.VaiTro", b =>
                {
                    b.Property<string>("MaVT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVT");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("WEBAPI.Data.VaiTro_NguoiDung", b =>
                {
                    b.Property<string>("MaVT")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaND")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("MaVT", "MaND");

                    b.HasIndex("MaND");

                    b.ToTable("VaiTro_NguoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.Xe", b =>
                {
                    b.Property<string>("MaXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("BienSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongSuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdDanhMuc")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdLoaiXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdMauXe")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("KhoiLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSX")
                        .HasColumnType("int");

                    b.Property<string>("SoKhung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaXe");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdLoaiXe");

                    b.HasIndex("IdMauXe");

                    b.ToTable("Xe");
                });

            modelBuilder.Entity("WEBAPI.Data.AnhNoiDung", b =>
                {
                    b.HasOne("WEBAPI.Data.NoiDung", "NoiDung")
                        .WithMany("AnhNoiDungs")
                        .HasForeignKey("MaNoiDung");

                    b.Navigation("NoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.BaiViet", b =>
                {
                    b.HasOne("WEBAPI.Data.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WEBAPI.Data.BangGia", b =>
                {
                    b.HasOne("WEBAPI.Data.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("WEBAPI.Data.ChiTietDonThue", b =>
                {
                    b.HasOne("WEBAPI.Data.DonThue", "DonThue")
                        .WithMany("chiTietDonThues")
                        .HasForeignKey("MaDT");

                    b.Navigation("DonThue");
                });

            modelBuilder.Entity("WEBAPI.Data.DonThue", b =>
                {
                    b.HasOne("WEBAPI.Data.NguoiDung", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH");

                    b.HasOne("WEBAPI.Data.NguoiDung", "NhanVienHoTro")
                        .WithMany()
                        .HasForeignKey("MaNVHT");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienHoTro");
                });

            modelBuilder.Entity("WEBAPI.Data.DonThue_DichVu", b =>
                {
                    b.HasOne("WEBAPI.Data.DonThue", "DonThue")
                        .WithMany("donThue_DichVus")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBAPI.Data.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("DonThue");
                });

            modelBuilder.Entity("WEBAPI.Data.GopY", b =>
                {
                    b.HasOne("WEBAPI.Data.DonThue", "DonThue")
                        .WithMany("gopYs")
                        .HasForeignKey("MaDT");

                    b.Navigation("DonThue");
                });

            modelBuilder.Entity("WEBAPI.Data.NoiDung", b =>
                {
                    b.HasOne("WEBAPI.Data.BaiViet", "BaiViet")
                        .WithMany("noiDungs")
                        .HasForeignKey("MaBV");

                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("WEBAPI.Data.VaiTro_NguoiDung", b =>
                {
                    b.HasOne("WEBAPI.Data.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBAPI.Data.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WEBAPI.Data.Xe", b =>
                {
                    b.HasOne("WEBAPI.Data.DanhMucXe", "DanhMucXe")
                        .WithMany("Xes")
                        .HasForeignKey("IdDanhMuc");

                    b.HasOne("WEBAPI.Data.LoaiXe", "LoaiXe")
                        .WithMany("Xes")
                        .HasForeignKey("IdLoaiXe");

                    b.HasOne("WEBAPI.Data.MauXe", "MauXe")
                        .WithMany("Xes")
                        .HasForeignKey("IdMauXe");

                    b.Navigation("DanhMucXe");

                    b.Navigation("LoaiXe");

                    b.Navigation("MauXe");
                });

            modelBuilder.Entity("WEBAPI.Data.BaiViet", b =>
                {
                    b.Navigation("noiDungs");
                });

            modelBuilder.Entity("WEBAPI.Data.DanhMucXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("WEBAPI.Data.DonThue", b =>
                {
                    b.Navigation("chiTietDonThues");

                    b.Navigation("donThue_DichVus");

                    b.Navigation("gopYs");
                });

            modelBuilder.Entity("WEBAPI.Data.LoaiXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("WEBAPI.Data.MauXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("WEBAPI.Data.NoiDung", b =>
                {
                    b.Navigation("AnhNoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
